discourse_rewards:
  discourse_rewards_enabled:
    default: true
    client: true
  discourse_rewards_points_for_bronze_badges:
    client: true
    default: 100
  discourse_rewards_points_for_silver_badges:
    client: true
    default: 200
  discourse_rewards_points_for_gold_badges:
    client: true
    default: 300
  discourse_rewards_grant_topic_category:
    type: category
    default: ""
  discourse_rewards_points_for_post_create:
    client: true
    default: 0
  discourse_rewards_points_for_topic_create:
    client: true
    default: 0
  discourse_rewards_points_for_like_received:
    client: true
    default: 0
  discourse_rewards_points_for_like_given:
    client: true
    default: 0
  discourse_rewards_points_for_daily_login:
    client: true
    default: 0
  discourse_rewards_show_points_on_site_header:
    client: true
    default: true
  discourse_rewards_daily_top_topics_to_grant_points:
    client: true
    default: 0
  discourse_rewards_daily_top_replies_to_grant_points:
    client: true
    default: 0
  discourse_rewards_daily_top_like_received_to_grant_points:
    client: true
    default: 0
  discourse_rewards_lottery_limit_per_day:
    client: true
    default: 5
  discourse_rewards_lottery_points_spent_per_time:
    client: true
    default: 20
  discourse_rewards_lottery_probability:
    type: list
    client: true
    default: "0.6|0.35|0.05"
  discourse_rewards_lottery_prizes:
    type: list
    client: true
    default: "10|40|100"
  discourse_rewards_rewards_types:
    type: list
    client: true
    default: "头像框|实物周边|其他"
